package com.iti.PlacementsBackend.repo.master;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.iti.PlacementsBackend.entity.master.OldDistMasterEntity;
import com.iti.PlacementsBackend.projection.DashBoardAllSeatsProj;
import com.iti.PlacementsBackend.projection.DashBoardGovtOrPvtSeatsProj;
import com.iti.PlacementsBackend.projection.ITIsSeatsStatisticsProj;


public interface OldDistMasterRepo extends JpaRepository<OldDistMasterEntity, String> {
	
	
	//above20percentcollegescountgovt
		@Query(value = "SELECT COUNT(*) AS above20percentcollegescountgovt\r\n"
				+ "FROM (\r\n"
				+ "    SELECT \r\n"
				+ "        a.iti_code,\r\n"
				+ "        a.iti_name,\r\n"
				+ "        SUM(strength) AS strength,\r\n"
				+ "        SUM(strength_fill) AS strength_fill,\r\n"
				+ "        ROUND(\r\n"
				+ "            CASE \r\n"
				+ "                WHEN SUM(strength) > 0 THEN (SUM(strength_fill)::DECIMAL / SUM(strength)) * 100\r\n"
				+ "                ELSE 0 \r\n"
				+ "            END, 2\r\n"
				+ "        ) AS fill_ratio\r\n"
				+ "    FROM \r\n"
				+ "        (\r\n"
				+ "            SELECT    \r\n"
				+ "                iti.iti_code,\r\n"
				+ "                iti.iti_name,\r\n"
				+ "                (SELECT SUM(value::DECIMAL) \r\n"
				+ "                 FROM iti_seatmatrix a, EACH(strength) \r\n"
				+ "                 WHERE a.iti_code = iti.iti_code \r\n"
				+ "                 AND year = '2024' \r\n"
				+ "                 AND iti.govt = 'G') AS strength,\r\n"
				+ "                (SELECT COUNT(*) \r\n"
				+ "                 FROM admissions.iti_admissions b \r\n"
				+ "                 WHERE year_of_admission = '2024' \r\n"
				+ "                 AND b.iti_code = iti.iti_code \r\n"
				+ "                 AND iti.govt = 'G') AS strength_fill \r\n"
				+ "            FROM iti   \r\n"
				+ "            LEFT JOIN iti_seatmatrix ON iti_seatmatrix.iti_code = iti.iti_code \r\n"
				+ "            WHERE iti_seatmatrix.year = '2024' \r\n"
				+ "            AND iti.govt = 'G' \r\n"
				+ "            GROUP BY iti.iti_code \r\n"
				+ "            ORDER BY dist_code\r\n"
				+ "        ) a \r\n"
				+ "    GROUP BY a.iti_code, a.iti_name\r\n"
				+ "    HAVING \r\n"
				+ "        ROUND(\r\n"
				+ "            CASE \r\n"
				+ "                WHEN SUM(strength) > 0 THEN (SUM(strength_fill)::DECIMAL / SUM(strength)) * 100\r\n"
				+ "                ELSE 0 \r\n"
				+ "            END, 2\r\n"
				+ "        ) > 20\r\n"
				+ ") AS result;",nativeQuery = true)
		public Long getAbove20percentcollegescountgovt();
		
		//below20percentcollegescountgovt
		@Query(value = "SELECT COUNT(*) AS below20percentcollegescountgovt\r\n"
				+ "FROM (\r\n"
				+ "    SELECT \r\n"
				+ "        a.iti_code,\r\n"
				+ "        a.iti_name,\r\n"
				+ "        SUM(strength) AS strength,\r\n"
				+ "        SUM(strength_fill) AS strength_fill,\r\n"
				+ "        ROUND(\r\n"
				+ "            CASE \r\n"
				+ "                WHEN SUM(strength) > 0 THEN (SUM(strength_fill)::DECIMAL / SUM(strength)) * 100\r\n"
				+ "                ELSE 0 \r\n"
				+ "            END, 2\r\n"
				+ "        ) AS fill_ratio\r\n"
				+ "    FROM \r\n"
				+ "        (\r\n"
				+ "            SELECT    \r\n"
				+ "                iti.iti_code,\r\n"
				+ "                iti.iti_name,\r\n"
				+ "                (SELECT SUM(value::DECIMAL) \r\n"
				+ "                 FROM iti_seatmatrix a, EACH(strength) \r\n"
				+ "                 WHERE a.iti_code = iti.iti_code \r\n"
				+ "                 AND year = '2024' \r\n"
				+ "                 AND iti.govt = 'G') AS strength,\r\n"
				+ "                (SELECT COUNT(*) \r\n"
				+ "                 FROM admissions.iti_admissions b \r\n"
				+ "                 WHERE year_of_admission = '2024' \r\n"
				+ "                 AND b.iti_code = iti.iti_code \r\n"
				+ "                 AND iti.govt = 'G') AS strength_fill \r\n"
				+ "            FROM iti   \r\n"
				+ "            LEFT JOIN iti_seatmatrix ON iti_seatmatrix.iti_code = iti.iti_code \r\n"
				+ "            WHERE iti_seatmatrix.year = '2024' \r\n"
				+ "            AND iti.govt = 'G' \r\n"
				+ "            GROUP BY iti.iti_code \r\n"
				+ "            ORDER BY dist_code\r\n"
				+ "        ) a \r\n"
				+ "    GROUP BY a.iti_code, a.iti_name\r\n"
				+ "    HAVING \r\n"
				+ "        ROUND(\r\n"
				+ "            CASE \r\n"
				+ "                WHEN SUM(strength) > 0 THEN (SUM(strength_fill)::DECIMAL / SUM(strength)) * 100\r\n"
				+ "                ELSE 0 \r\n"
				+ "            END, 2\r\n"
				+ "        ) < 20\r\n"
				+ ") AS result;",nativeQuery = true)
		public Long getBelow20percentcollegescountgovt();
		
		//above20percentcollegescountpvt
		@Query(value = "SELECT COUNT(*) AS above20percentcollegescountpvt\r\n"
				+ "FROM (\r\n"
				+ "    SELECT \r\n"
				+ "        a.iti_code,\r\n"
				+ "        a.iti_name,\r\n"
				+ "        SUM(strength) AS strength,\r\n"
				+ "        SUM(strength_fill) AS strength_fill,\r\n"
				+ "        ROUND(\r\n"
				+ "            CASE \r\n"
				+ "                WHEN SUM(strength) > 0 THEN (SUM(strength_fill)::DECIMAL / SUM(strength)) * 100\r\n"
				+ "                ELSE 0 \r\n"
				+ "            END, 2\r\n"
				+ "        ) AS fill_ratio\r\n"
				+ "    FROM \r\n"
				+ "        (\r\n"
				+ "            SELECT    \r\n"
				+ "                iti.iti_code,\r\n"
				+ "                iti.iti_name,\r\n"
				+ "                (SELECT SUM(value::DECIMAL) \r\n"
				+ "                 FROM iti_seatmatrix a, EACH(strength) \r\n"
				+ "                 WHERE a.iti_code = iti.iti_code \r\n"
				+ "                 AND year = '2024' \r\n"
				+ "                 AND iti.govt = 'P') AS strength,\r\n"
				+ "                (SELECT COUNT(*) \r\n"
				+ "                 FROM admissions.iti_admissions b \r\n"
				+ "                 WHERE year_of_admission = '2024' \r\n"
				+ "                 AND b.iti_code = iti.iti_code \r\n"
				+ "                 AND iti.govt = 'P') AS strength_fill \r\n"
				+ "            FROM iti   \r\n"
				+ "            LEFT JOIN iti_seatmatrix ON iti_seatmatrix.iti_code = iti.iti_code \r\n"
				+ "            WHERE iti_seatmatrix.year = '2024' \r\n"
				+ "            AND iti.govt = 'P' \r\n"
				+ "            GROUP BY iti.iti_code \r\n"
				+ "            ORDER BY dist_code\r\n"
				+ "        ) a \r\n"
				+ "    GROUP BY a.iti_code, a.iti_name\r\n"
				+ "    HAVING \r\n"
				+ "        ROUND(\r\n"
				+ "            CASE \r\n"
				+ "                WHEN SUM(strength) > 0 THEN (SUM(strength_fill)::DECIMAL / SUM(strength)) * 100\r\n"
				+ "                ELSE 0 \r\n"
				+ "            END, 2\r\n"
				+ "        ) > 20\r\n"
				+ ") AS result;",nativeQuery = true)
		public Long getAbove20percentcollegescountpvt();
		
		//below20percentcollegescountpvt
		@Query(value = "SELECT COUNT(*) AS below20percentcollegescountpvt\r\n"
				+ "FROM (\r\n"
				+ "    SELECT \r\n"
				+ "        a.iti_code,\r\n"
				+ "        a.iti_name,\r\n"
				+ "        SUM(strength) AS strength,\r\n"
				+ "        SUM(strength_fill) AS strength_fill,\r\n"
				+ "        ROUND(\r\n"
				+ "            CASE \r\n"
				+ "                WHEN SUM(strength) > 0 THEN (SUM(strength_fill)::DECIMAL / SUM(strength)) * 100\r\n"
				+ "                ELSE 0 \r\n"
				+ "            END, 2\r\n"
				+ "        ) AS fill_ratio\r\n"
				+ "    FROM \r\n"
				+ "        (\r\n"
				+ "            SELECT    \r\n"
				+ "                iti.iti_code,\r\n"
				+ "                iti.iti_name,\r\n"
				+ "                (SELECT SUM(value::DECIMAL) \r\n"
				+ "                 FROM iti_seatmatrix a, EACH(strength) \r\n"
				+ "                 WHERE a.iti_code = iti.iti_code \r\n"
				+ "                 AND year = '2024' \r\n"
				+ "                 AND iti.govt = 'P') AS strength,\r\n"
				+ "                (SELECT COUNT(*) \r\n"
				+ "                 FROM admissions.iti_admissions b \r\n"
				+ "                 WHERE year_of_admission = '2024' \r\n"
				+ "                 AND b.iti_code = iti.iti_code \r\n"
				+ "                 AND iti.govt = 'P') AS strength_fill \r\n"
				+ "            FROM iti   \r\n"
				+ "            LEFT JOIN iti_seatmatrix ON iti_seatmatrix.iti_code = iti.iti_code \r\n"
				+ "            WHERE iti_seatmatrix.year = '2024' \r\n"
				+ "            AND iti.govt = 'P' \r\n"
				+ "            GROUP BY iti.iti_code \r\n"
				+ "            ORDER BY dist_code\r\n"
				+ "        ) a \r\n"
				+ "    GROUP BY a.iti_code, a.iti_name\r\n"
				+ "    HAVING \r\n"
				+ "        ROUND(\r\n"
				+ "            CASE \r\n"
				+ "                WHEN SUM(strength) > 0 THEN (SUM(strength_fill)::DECIMAL / SUM(strength)) * 100\r\n"
				+ "                ELSE 0 \r\n"
				+ "            END, 2\r\n"
				+ "        ) < 20\r\n"
				+ ") AS result;",nativeQuery = true)
		public Long getBelow20percentcollegescountpvt();
		
		//DashBoardAllSeatsProj
		@Query(value = "SELECT  \r\n"
				+ "    SUM(strength) AS strength,\r\n"
				+ "    SUM(strength_fill) AS strength_fill,\r\n"
				+ "    SUM(strength - strength_fill) AS strength_vacant,\r\n"
				+ "	ROUND(\r\n"
				+ "        CASE \r\n"
				+ "            WHEN SUM(strength) > 0 THEN (SUM(strength_fill)::DECIMAL / SUM(strength)) * 100\r\n"
				+ "            ELSE 0 \r\n"
				+ "        END, 2\r\n"
				+ "    ) AS fill_ratio\r\n"
				+ "FROM (\r\n"
				+ "    SELECT   \r\n"
				+ "        (SELECT SUM(value::DECIMAL) \r\n"
				+ "         FROM iti_seatmatrix a, EACH(strength) \r\n"
				+ "         WHERE a.iti_code = iti.iti_code \r\n"
				+ "         AND year = '2024' \r\n"
				+ "          ) AS strength,\r\n"
				+ "         \r\n"
				+ "        (SELECT COUNT(*) \r\n"
				+ "         FROM admissions.iti_admissions b \r\n"
				+ "         WHERE year_of_admission = '2024' \r\n"
				+ "         AND b.iti_code = iti.iti_code \r\n"
				+ "          ) AS strength_fill\r\n"
				+ "         \r\n"
				+ "    FROM iti   \r\n"
				+ "    LEFT JOIN iti_seatmatrix ON iti_seatmatrix.iti_code = iti.iti_code \r\n"
				+ "    WHERE iti_seatmatrix.year = '2024' \r\n"
				+ "    \r\n"
				+ "    GROUP BY iti.iti_code \r\n"
				+ "    ORDER BY dist_code\r\n"
				+ ") a;",nativeQuery = true)
		public DashBoardAllSeatsProj getDashBoardAllSeats();
		
		//getDashBoardGovtOrPvtSeats
		@Query(value = "SELECT  \r\n"
				+ "    SUM(strength) AS strength,\r\n"
				+ "    SUM(strength_fill) AS strength_fill,\r\n"
				+ "    SUM(strength - strength_fill) AS strength_vacant,\r\n"
				+ "	ROUND(\r\n"
				+ "        CASE \r\n"
				+ "            WHEN SUM(strength) > 0 THEN (SUM(strength_fill)::DECIMAL / SUM(strength)) * 100\r\n"
				+ "            ELSE 0 \r\n"
				+ "        END, 2\r\n"
				+ "    ) AS fill_ratio\r\n"
				+ "FROM (\r\n"
				+ "    SELECT   \r\n"
				+ "        (SELECT SUM(value::DECIMAL) \r\n"
				+ "         FROM iti_seatmatrix a, EACH(strength) \r\n"
				+ "         WHERE a.iti_code = iti.iti_code \r\n"
				+ "         AND year = '2024' \r\n"
				+ "         AND iti.govt = :govt) AS strength,\r\n"
				+ "         \r\n"
				+ "        (SELECT COUNT(*) \r\n"
				+ "         FROM admissions.iti_admissions b \r\n"
				+ "         WHERE year_of_admission = '2024' \r\n"
				+ "         AND b.iti_code = iti.iti_code \r\n"
				+ "         AND iti.govt = :govt) AS strength_fill\r\n"
				+ "         \r\n"
				+ "    FROM iti   \r\n"
				+ "    LEFT JOIN iti_seatmatrix ON iti_seatmatrix.iti_code = iti.iti_code \r\n"
				+ "    WHERE iti_seatmatrix.year = '2024' \r\n"
				+ "    AND iti.govt = :govt \r\n"
				+ "    GROUP BY iti.iti_code \r\n"
				+ "    ORDER BY dist_code\r\n"
				+ ") a;",nativeQuery = true)
		public DashBoardGovtOrPvtSeatsProj getDashBoardGovtOrPvtSeats(String govt);
		
		
		
		@Query(value="SELECT  d.dist_code,  d.dist_name, a.iti_code, a.iti_name,case when SUM(a.strength)>0 then SUM(a.strength) else 0 \r\n"
				+ "end AS strength, SUM(a.strength_fill) AS strength_fill, case when SUM(strength - strength_fill)>0 \r\n"
				+ "then sum(strength - strength_fill) else 0 end AS strength_vacant, \r\n"
				+ "ROUND(  CASE  WHEN SUM(a.strength) > 0 THEN (SUM(a.strength_fill)::DECIMAL / SUM(a.strength)) * 100 ELSE 0 END, 2 \r\n"
				+ ") AS fill_ratio  FROM ( SELECT iti.iti_code, iti.iti_name, iti.dist_code, (SELECT SUM(value::DECIMAL) FROM \r\n"
				+ "iti_seatmatrix a, EACH(strength) WHERE a.iti_code = iti.iti_code AND year = '2024') AS strength, (SELECT COUNT(*) \r\n"
				+ "FROM admissions.iti_admissions b WHERE year_of_admission = '2024' AND b.iti_code = iti.iti_code  ) AS strength_fill  \r\n"
				+ "FROM iti LEFT JOIN iti_seatmatrix ON iti_seatmatrix.iti_code = iti.iti_code AND iti_seatmatrix.year = '2024' GROUP \r\n"
				+ "BY iti.iti_code, iti.dist_code ) a JOIN dist_mst d ON a.dist_code = d.dist_code GROUP BY a.iti_code, a.iti_name, \r\n"
				+ "d.dist_code, d.dist_name HAVING ROUND( CASE WHEN SUM(a.strength) > 0 THEN (SUM(a.strength_fill)::DECIMAL / \r\n"
				+ "SUM(a.strength)) * 100 ELSE 0 END, 2 ) >= 20 ORDER BY d.dist_code;", nativeQuery = true)
		public List<ITIsSeatsStatisticsProj> getAbove20PercentItis();
		@Query(value="SELECT  d.dist_code,  d.dist_name, a.iti_code, a.iti_name,case when SUM(a.strength)>0 then SUM(a.strength) else 0 \r\n"
				+ "end AS strength, SUM(a.strength_fill) AS strength_fill, case when SUM(strength - strength_fill)>0 \r\n"
				+ "then sum(strength - strength_fill) else 0 end AS strength_vacant, \r\n"
				+ "ROUND(  CASE  WHEN SUM(a.strength) > 0 THEN (SUM(a.strength_fill)::DECIMAL / SUM(a.strength)) * 100 ELSE 0 END, 2 \r\n"
				+ ") AS fill_ratio  FROM ( SELECT iti.iti_code, iti.iti_name, iti.dist_code, (SELECT SUM(value::DECIMAL) FROM \r\n"
				+ "iti_seatmatrix a, EACH(strength) WHERE a.iti_code = iti.iti_code AND year = '2024') AS strength, (SELECT COUNT(*) \r\n"
				+ "FROM admissions.iti_admissions b WHERE year_of_admission = '2024' AND b.iti_code = iti.iti_code  ) AS strength_fill  \r\n"
				+ "FROM iti LEFT JOIN iti_seatmatrix ON iti_seatmatrix.iti_code = iti.iti_code AND iti_seatmatrix.year = '2024' GROUP \r\n"
				+ "BY iti.iti_code, iti.dist_code ) a JOIN dist_mst d ON a.dist_code = d.dist_code GROUP BY a.iti_code, a.iti_name, \r\n"
				+ "d.dist_code, d.dist_name HAVING ROUND( CASE WHEN SUM(a.strength) > 0 THEN (SUM(a.strength_fill)::DECIMAL / \r\n"
				+ "SUM(a.strength)) * 100 ELSE 0 END, 2 ) < 20 ORDER BY d.dist_code;", nativeQuery = true)
		public List<ITIsSeatsStatisticsProj> getBelow20PercentItis();
		
		
		@Query(value="SELECT  SUM(a.strength) AS  strength,  SUM(a.strength_fill) AS  strength_fill, \r\n"
				+ "SUM(a.strength - a.strength_fill) AS  strength_vacant,\r\n"
				+ "ROUND( CASE  WHEN SUM(a.strength) > 0 THEN (SUM(a.strength_fill)::DECIMAL / SUM(a.strength)) * 100 ELSE 0 END, 2 ) AS  fill_ratio\r\n"
				+ "FROM ( \r\n"
				+ "SELECT iti.iti_code, iti.iti_name, iti.dist_code,  \r\n"
				+ "(SELECT SUM(value::DECIMAL) FROM iti_seatmatrix a, EACH(strength) WHERE a.iti_code = iti.iti_code AND year = '2024') AS strength, \r\n"
				+ "(SELECT COUNT(*) FROM admissions.iti_admissions b WHERE year_of_admission = '2024' AND b.iti_code = iti.iti_code) AS strength_fill  \r\n"
				+ "FROM iti LEFT JOIN iti_seatmatrix ON iti_seatmatrix.iti_code = iti.iti_code AND iti_seatmatrix.year = '2024' \r\n"
				+ "GROUP BY iti.iti_code, iti.dist_code \r\n"
				+ ") a  \r\n"
				+ "HAVING  ROUND( CASE WHEN SUM(a.strength) > 0 THEN (SUM(a.strength_fill)::DECIMAL / SUM(a.strength)) * 100 ELSE 0  END, 2 ) >= 20;\r\n"
				+ "",nativeQuery = true)
		public ITIsSeatsStatisticsProj getAbove20PercentSeatsStats();
		@Query(value="SELECT  SUM(a.strength) AS  strength,  SUM(a.strength_fill) AS  strength_fill, \r\n"
				+ "SUM(a.strength - a.strength_fill) AS  strength_vacant,\r\n"
				+ "ROUND( CASE  WHEN SUM(a.strength) > 0 THEN (SUM(a.strength_fill)::DECIMAL / SUM(a.strength)) * 100 ELSE 0 END, 2 ) AS  fill_ratio\r\n"
				+ "FROM ( \r\n"
				+ "SELECT iti.iti_code, iti.iti_name, iti.dist_code,  \r\n"
				+ "(SELECT SUM(value::DECIMAL) FROM iti_seatmatrix a, EACH(strength) WHERE a.iti_code = iti.iti_code AND year = '2024') AS strength, \r\n"
				+ "(SELECT COUNT(*) FROM admissions.iti_admissions b WHERE year_of_admission = '2024' AND b.iti_code = iti.iti_code) AS strength_fill  \r\n"
				+ "FROM iti LEFT JOIN iti_seatmatrix ON iti_seatmatrix.iti_code = iti.iti_code AND iti_seatmatrix.year = '2024' \r\n"
				+ "GROUP BY iti.iti_code, iti.dist_code \r\n"
				+ ") a  \r\n"
				+ "HAVING  ROUND( CASE WHEN SUM(a.strength) > 0 THEN (SUM(a.strength_fill)::DECIMAL / SUM(a.strength)) * 100 ELSE 0  END, 2 ) < 20;\r\n"
				+ "",nativeQuery = true)
		public ITIsSeatsStatisticsProj getBelow20PercentSeatsStats();
		
	 

}
